export const molecule_risk = [
    {
        Molecule_ID: '102322-83-8',
        Molecule: '2-Hepten-4-one, 5-methyl-, (2E)-',
        Clas_ID: 'H226',
        Clas: 'Flam. Liq. 3',
    },
    {
        Molecule_ID: '102322-83-8',
        Molecule: '2-Hepten-4-one, 5-methyl-, (2E)-',
        Clas_ID: 'H302',
        Clas: 'Acute Tox. 4 Oral',
    },
    {
        Molecule_ID: '102322-83-8',
        Molecule: '2-Hepten-4-one, 5-methyl-, (2E)-',
        Clas_ID: 'H315',
        Clas: 'Skin Irrit. 2',
    },
    {
        Molecule_ID: '102322-83-8',
        Molecule: '2-Hepten-4-one, 5-methyl-, (2E)-',
        Clas_ID: 'H317-1A',
        Clas: 'Skin Sens. 1A',
    },
    {
        Molecule_ID: '105-13-5',
        Molecule: '4-methoxybenzyl alcohol',
        Clas_ID: 'H302',
        Clas: 'Acute Tox. 4 Oral',
    },
    {
        Molecule_ID: '105-13-5',
        Molecule: '4-methoxybenzyl alcohol',
        Clas_ID: 'H317-1',
        Clas: 'Skin Sens. 1',
    },
    {
        Molecule_ID: '105-13-5',
        Molecule: '4-methoxybenzyl alcohol',
        Clas_ID: 'H318',
        Clas: 'Eye Dam. 1',
    },
    {
        Molecule_ID: '106-22-9',
        Molecule: 'DL-Citronellol',
        Clas_ID: 'H315',
        Clas: 'Skin Irrit. 2',
    },
    {
        Molecule_ID: '106-22-9',
        Molecule: 'DL-Citronellol',
        Clas_ID: 'H317-1B',
        Clas: 'Skin Sens. 1B',
    },
    {
        Molecule_ID: '106-22-9',
        Molecule: 'DL-Citronellol',
        Clas_ID: 'H319',
        Clas: 'Eye Irrit. 2',
    },
    {
        Molecule_ID: '106-24-1',
        Molecule: 'geraniol',
        Clas_ID: 'H315',
        Clas: 'Skin Irrit. 2',
    },
    {
        Molecule_ID: '106-24-1',
        Molecule: 'geraniol',
        Clas_ID: 'H317-1',
        Clas: 'Skin Sens. 1',
    },
    {
        Molecule_ID: '106-24-1',
        Molecule: 'geraniol',
        Clas_ID: 'H318',
        Clas: 'Eye Dam. 1',
    },
    {
        Molecule_ID: '110-19-0',
        Molecule: "acétate d'isobutyle",
        Clas_ID: 'H225',
        Clas: 'Flam. Liq. 2',
    },
    {
        Molecule_ID: '119-84-6',
        Molecule: '3,4-dihydrocoumarin',
        Clas_ID: 'H302',
        Clas: 'Acute Tox. 4 Oral',
    },
    {
        Molecule_ID: '119-84-6',
        Molecule: '3,4-dihydrocoumarin',
        Clas_ID: 'H317-1',
        Clas: 'Skin Sens. 1',
    },
    {
        Molecule_ID: '121-33-5',
        Molecule: 'vanillin',
        Clas_ID: 'H319',
        Clas: 'Eye Irrit. 2',
    },
    {
        Molecule_ID: '123-51-3',
        Molecule: '3-methylbutan-1-ol',
        Clas_ID: 'H226',
        Clas: 'Flam. Liq. 3',
    },
    {
        Molecule_ID: '123-51-3',
        Molecule: '3-methylbutan-1-ol',
        Clas_ID: 'H315',
        Clas: 'Skin Irrit. 2',
    },
    {
        Molecule_ID: '123-51-3',
        Molecule: '3-methylbutan-1-ol',
        Clas_ID: 'H319',
        Clas: 'Eye Irrit. 2',
    },
    {
        Molecule_ID: '123-51-3',
        Molecule: '3-methylbutan-1-ol',
        Clas_ID: 'H332',
        Clas: 'Acute Tox. 4 Inhalation',
    },
    {
        Molecule_ID: '123-51-3',
        Molecule: '3-methylbutan-1-ol',
        Clas_ID: 'H335',
        Clas: 'STOT SE 3 (H335)',
    },
    {
        Molecule_ID: '123-68-2',
        Molecule: 'allyl hexanoate',
        Clas_ID: 'H301',
        Clas: 'Acute Tox. 3 Oral',
    },
    {
        Molecule_ID: '123-68-2',
        Molecule: 'allyl hexanoate',
        Clas_ID: 'H311',
        Clas: 'Acute Tox. 3 Dermal',
    },
    {
        Molecule_ID: '123-68-2',
        Molecule: 'allyl hexanoate',
        Clas_ID: 'H331',
        Clas: 'Acute Tox. 3 Inhalation',
    },
    {
        Molecule_ID: '123-68-2',
        Molecule: 'allyl hexanoate',
        Clas_ID: 'H400',
        Clas: 'Aquatic Acute 1',
    },
    {
        Molecule_ID: '123-68-2',
        Molecule: 'allyl hexanoate',
        Clas_ID: 'H412',
        Clas: 'Aquatic Chronic 3',
    },
    {
        Molecule_ID: '123-92-2',
        Molecule: "acétate d'isopentyle",
        Clas_ID: 'H226',
        Clas: 'Flam. Liq. 3',
    },
    {
        Molecule_ID: '14073-97-3',
        Molecule: 'L-menthan-3-one',
        Clas_ID: 'H315',
        Clas: 'Skin Irrit. 2',
    },
    {
        Molecule_ID: '14073-97-3',
        Molecule: 'L-menthan-3-one',
        Clas_ID: 'H317-1B',
        Clas: 'Skin Sens. 1B',
    },
    {
        Molecule_ID: '141-25-3',
        Molecule: '3,7-dimethyloct-7-en-1-ol',
        Clas_ID: 'H315',
        Clas: 'Skin Irrit. 2',
    },
    {
        Molecule_ID: '141-25-3',
        Molecule: '3,7-dimethyloct-7-en-1-ol',
        Clas_ID: 'H317-1',
        Clas: 'Skin Sens. 1',
    },
    {
        Molecule_ID: '141-25-3',
        Molecule: '3,7-dimethyloct-7-en-1-ol',
        Clas_ID: 'H318',
        Clas: 'Eye Dam. 1',
    },
    {
        Molecule_ID: '141-78-6',
        Molecule: "acétate d'éthyle",
        Clas_ID: 'H225',
        Clas: 'Flam. Liq. 2',
    },
    {
        Molecule_ID: '141-78-6',
        Molecule: "acétate d'éthyle",
        Clas_ID: 'H319',
        Clas: 'Eye Irrit. 2',
    },
    {
        Molecule_ID: '141-78-6',
        Molecule: "acétate d'éthyle",
        Clas_ID: 'H336',
        Clas: 'STOT SE 3 (H336)',
    },
    {
        Molecule_ID: '14901-07-6',
        Molecule: '4-(2,6,6-trimethylcyclohex-1-ene-1-yl)-but-3-ene-2-one',
        Clas_ID: 'H411',
        Clas: 'Aquatic Chronic 2',
    },
    // {
    //     Molecule_ID: '16409-43-1',
    //     Molecule: 'tetrahydro-4-methyl-2-(2-methylprop-1-enyl)pyran',
    //     Clas_ID: 'H315',
    //     Clas: 'Skin Irrit. 2',
    // },
    // {
    //     Molecule_ID: '16409-43-1',
    //     Molecule: 'tetrahydro-4-methyl-2-(2-methylprop-1-enyl)pyran',
    //     Clas_ID: 'H319',
    //     Clas: 'Eye Irrit. 2',
    // },
    // {
    //     Molecule_ID: '16409-43-1',
    //     Molecule: 'tetrahydro-4-methyl-2-(2-methylprop-1-enyl)pyran',
    //     Clas_ID: 'H361',
    //     Clas: 'Repr. 2',
    // },
    {
        Molecule_ID: '21834-92-4',
        Molecule: '5-methyl-2-phenylhex-2-enal',
        Clas_ID: 'H317-1',
        Clas: 'Skin Sens. 1',
    },
    {
        Molecule_ID: '2216-51-5',
        Molecule: 'L-menthol',
        Clas_ID: 'H315',
        Clas: 'Skin Irrit. 2',
    },
    {
        Molecule_ID: '2216-51-5',
        Molecule: 'L-menthol',
        Clas_ID: 'H319',
        Clas: 'Eye Irrit. 2',
    },
    {
        Molecule_ID: '23696-85-7',
        Molecule: '1-(2,6,6-trimethyl-1,3-cyclohe xadien-1-yl)-2-buten-1-one',
        Clas_ID: 'H315',
        Clas: 'Skin Irrit. 2',
    },
    {
        Molecule_ID: '23696-85-7',
        Molecule: '1-(2,6,6-trimethyl-1,3-cyclohe xadien-1-yl)-2-buten-1-one',
        Clas_ID: 'H317-1A',
        Clas: 'Skin Sens. 1A',
    },
    {
        Molecule_ID: '23696-85-7',
        Molecule: '1-(2,6,6-trimethyl-1,3-cyclohe xadien-1-yl)-2-buten-1-one',
        Clas_ID: 'H411',
        Clas: 'Aquatic Chronic 2',
    },
    {
        Molecule_ID: '3658-77-3',
        Molecule: '4-hydroxy-2,5-dimethylfuran-2 (3H)-one',
        Clas_ID: 'H317-1A',
        Clas: 'Skin Sens. 1A',
    },
    {
        Molecule_ID: '3658-77-3',
        Molecule: '4-hydroxy-2,5-dimethylfuran-2 (3H)-one',
        Clas_ID: 'H319',
        Clas: 'Eye Irrit. 2',
    },
    {
        Molecule_ID: '38462-22-5',
        Molecule: 'para-mentha-8-thiolone',
        Clas_ID: 'H317-1',
        Clas: 'Skin Sens. 1',
    },
    {
        Molecule_ID: '4180-23-8',
        Molecule: '(E)-anethole',
        Clas_ID: 'H317-1',
        Clas: 'Skin Sens. 1',
    },
    {
        Molecule_ID: '491-07-6',
        Molecule: 'isomenthone',
        Clas_ID: 'H315',
        Clas: 'Skin Irrit. 2',
    },
    {
        Molecule_ID: '491-07-6',
        Molecule: 'isomenthone',
        Clas_ID: 'H317-1',
        Clas: 'Skin Sens. 1',
    },
    {
        Molecule_ID: '4940-11-8',
        Molecule: '2-ethyl-3-hydroxy-4-pyrone',
        Clas_ID: 'H302',
        Clas: 'Acute Tox. 4 Oral',
    },
    {
        Molecule_ID: '5392-40-5',
        Molecule: 'citral',
        Clas_ID: 'H315',
        Clas: 'Skin Irrit. 2',
    },
    {
        Molecule_ID: '5392-40-5',
        Molecule: 'citral',
        Clas_ID: 'H317-1',
        Clas: 'Skin Sens. 1',
    },
    {
        Molecule_ID: '5392-40-5',
        Molecule: 'citral',
        Clas_ID: 'H319',
        Clas: 'Eye Irrit. 2',
    },
    {
        Molecule_ID: '56-81-5',
        Molecule: 'glycerol',
        Clas_ID: '(vide)',
        Clas: 'Not Classified',
    },
    {
        Molecule_ID: '590-86-3',
        Molecule: 'isovaleraldehyde',
        Clas_ID: 'H225',
        Clas: 'Flam. Liq. 2',
    },
    {
        Molecule_ID: '590-86-3',
        Molecule: 'isovaleraldehyde',
        Clas_ID: 'H317-1B',
        Clas: 'Skin Sens. 1B',
    },
    {
        Molecule_ID: '590-86-3',
        Molecule: 'isovaleraldehyde',
        Clas_ID: 'H319',
        Clas: 'Eye Irrit. 2',
    },
    {
        Molecule_ID: '590-86-3',
        Molecule: 'isovaleraldehyde',
        Clas_ID: 'H335',
        Clas: 'STOT SE 3 (H335)',
    },
    {
        Molecule_ID: '590-86-3',
        Molecule: 'isovaleraldehyde',
        Clas_ID: 'H411',
        Clas: 'Aquatic Chronic 2',
    },
    {
        Molecule_ID: '628-63-7',
        Molecule: 'Amyl acetate common',
        Clas_ID: 'H226',
        Clas: 'Flam. Liq. 3',
    },
    {
        Molecule_ID: '64-17-5',
        Molecule: 'éthanol, alcool éthylique',
        Clas_ID: 'H225',
        Clas: 'Flam. Liq. 2',
    },
    {
        Molecule_ID: '64-19-7',
        Molecule: 'acide acétique',
        Clas_ID: 'H226',
        Clas: 'Flam. Liq. 3',
    },
    {
        Molecule_ID: '64-19-7',
        Molecule: 'acide acétique',
        Clas_ID: 'H314',
        Clas: 'Skin Corr. 1A',
    },
    {
        Molecule_ID: '7212-44-4',
        Molecule: '3,7,11-trimethyldodeca-1,6,10-trien-3-ol,mixed isomers',
        Clas_ID: 'H319',
        Clas: 'Eye Irrit. 2',
    },
    {
        Molecule_ID: '7212-44-4',
        Molecule: '3,7,11-trimethyldodeca-1,6,10-trien-3-ol,mixed isomers',
        Clas_ID: 'H410',
        Clas: 'Aquatic Chronic 1',
    },
    {
        Molecule_ID: '75-18-3',
        Molecule: 'dimethyl sulphide',
        Clas_ID: 'H225',
        Clas: 'Flam. Liq. 2',
    },
    {
        Molecule_ID: '75-18-3',
        Molecule: 'dimethyl sulphide',
        Clas_ID: 'H301',
        Clas: 'Acute Tox. 3 Oral',
    },
    {
        Molecule_ID: '77-83-8',
        Molecule: 'ethyl 2,3-epoxy-3-phenylbutyrate',
        Clas_ID: 'H317-1B',
        Clas: 'Skin Sens. 1B',
    },
    {
        Molecule_ID: '77-83-8',
        Molecule: 'ethyl 2,3-epoxy-3-phenylbutyrate',
        Clas_ID: 'H411',
        Clas: 'Aquatic Chronic 2',
    },
    {
        Molecule_ID: '78-70-6',
        Molecule: 'linalool',
        Clas_ID: 'H315',
        Clas: 'Skin Irrit. 2',
    },
    {
        Molecule_ID: '78-70-6',
        Molecule: 'linalool',
        Clas_ID: 'H317-1B',
        Clas: 'Skin Sens. 1B',
    },
    {
        Molecule_ID: '78-70-6',
        Molecule: 'linalool',
        Clas_ID: 'H319',
        Clas: 'Eye Irrit. 2',
    },
    {
        Molecule_ID: '8000-46-2',
        Molecule: 'Oils, geranium',
        Clas_ID: 'H304',
        Clas: 'Asp. Tox. 1',
    },
    {
        Molecule_ID: '8000-46-2',
        Molecule: 'Oils, geranium',
        Clas_ID: 'H315',
        Clas: 'Skin Irrit. 2',
    },
    {
        Molecule_ID: '8000-46-2',
        Molecule: 'Oils, geranium',
        Clas_ID: 'H317-1',
        Clas: 'Skin Sens. 1',
    },
    {
        Molecule_ID: '8000-46-2',
        Molecule: 'Oils, geranium',
        Clas_ID: 'H318',
        Clas: 'Eye Dam. 1',
    },
    {
        Molecule_ID: '8000-46-2',
        Molecule: 'Oils, geranium',
        Clas_ID: 'H412',
        Clas: 'Aquatic Chronic 3',
    },
    {
        Molecule_ID: '8000-48-4',
        Molecule: 'Eucalyptus globulus, ext.',
        Clas_ID: 'H226',
        Clas: 'Flam. Liq. 3',
    },
    {
        Molecule_ID: '8000-48-4',
        Molecule: 'Eucalyptus globulus, ext.',
        Clas_ID: 'H304',
        Clas: 'Asp. Tox. 1',
    },
    {
        Molecule_ID: '8000-48-4',
        Molecule: 'Eucalyptus globulus, ext.',
        Clas_ID: 'H317-1',
        Clas: 'Skin Sens. 1',
    },
    {
        Molecule_ID: '8000-48-4',
        Molecule: 'Eucalyptus globulus, ext.',
        Clas_ID: 'H411',
        Clas: 'Aquatic Chronic 2',
    },
    {
        Molecule_ID: '8007-00-9',
        Molecule: 'Balsams, Peru',
        Clas_ID: 'H302',
        Clas: 'Acute Tox. 4 Oral',
    },
    {
        Molecule_ID: '8007-00-9',
        Molecule: 'Balsams, Peru',
        Clas_ID: 'H317-1',
        Clas: 'Skin Sens. 1',
    },
    {
        Molecule_ID: '8007-00-9',
        Molecule: 'Balsams, Peru',
        Clas_ID: 'H411',
        Clas: 'Aquatic Chronic 2',
    },
    {
        Molecule_ID: '8008-26-2',
        Molecule: 'Extrait de citron. Citrus aurantifolia.',
        Clas_ID: 'H226',
        Clas: 'Flam. Liq. 3',
    },
    {
        Molecule_ID: '8008-26-2',
        Molecule: 'Extrait de citron. Citrus aurantifolia.',
        Clas_ID: 'H304',
        Clas: 'Asp. Tox. 1',
    },
    {
        Molecule_ID: '8008-26-2',
        Molecule: 'Extrait de citron. Citrus aurantifolia.',
        Clas_ID: 'H315',
        Clas: 'Skin Irrit. 2',
    },
    {
        Molecule_ID: '8008-26-2',
        Molecule: 'Extrait de citron. Citrus aurantifolia.',
        Clas_ID: 'H317-1',
        Clas: 'Skin Sens. 1',
    },
    {
        Molecule_ID: '8008-26-2',
        Molecule: 'Extrait de citron. Citrus aurantifolia.',
        Clas_ID: 'H410',
        Clas: 'Aquatic Chronic 1',
    },
    {
        Molecule_ID: '8008-56-8',
        Molecule: 'Lemon Oil',
        Clas_ID: 'H226',
        Clas: 'Flam. Liq. 3',
    },
    {
        Molecule_ID: '8008-56-8',
        Molecule: 'Lemon Oil',
        Clas_ID: 'H304',
        Clas: 'Asp. Tox. 1',
    },
    {
        Molecule_ID: '8008-56-8',
        Molecule: 'Lemon Oil',
        Clas_ID: 'H315',
        Clas: 'Skin Irrit. 2',
    },
    {
        Molecule_ID: '8008-56-8',
        Molecule: 'Lemon Oil',
        Clas_ID: 'H317-1',
        Clas: 'Skin Sens. 1',
    },
    {
        Molecule_ID: '8008-56-8',
        Molecule: 'Lemon Oil',
        Clas_ID: 'H319',
        Clas: 'Eye Irrit. 2',
    },
    {
        Molecule_ID: '8008-56-8',
        Molecule: 'Lemon Oil',
        Clas_ID: 'H400',
        Clas: 'Aquatic Acute 1',
    },
    {
        Molecule_ID: '8008-56-8',
        Molecule: 'Lemon Oil',
        Clas_ID: 'H410',
        Clas: 'Aquatic Chronic 1',
    },
    {
        Molecule_ID: '84961-46-6',
        Molecule: 'cinnamomum cassias ext.',
        Clas_ID: 'H304',
        Clas: 'Asp. Tox. 1',
    },
    {
        Molecule_ID: '84961-46-6',
        Molecule: 'cinnamomum cassias ext.',
        Clas_ID: 'H311',
        Clas: 'Acute Toxic 3 Dermal',
    },
    {
        Molecule_ID: '84961-46-6',
        Molecule: 'cinnamomum cassias ext.',
        Clas_ID: 'H315',
        Clas: 'Skin Irrit. 2',
    },
    {
        Molecule_ID: '84961-46-6',
        Molecule: 'cinnamomum cassias ext.',
        Clas_ID: 'H317-1',
        Clas: 'Skin Sens. 1',
    },
    {
        Molecule_ID: '84961-46-6',
        Molecule: 'cinnamomum cassias ext.',
        Clas_ID: 'H319',
        Clas: 'Eye Irrit. 2',
    },
    {
        Molecule_ID: '87-44-5',
        Molecule: 'caryophyllene',
        Clas_ID: 'H304',
        Clas: 'Asp. Tox. 1',
    },
    {
        Molecule_ID: '87-44-5',
        Molecule: 'caryophyllene',
        Clas_ID: 'H317-1B',
        Clas: 'Skin Sens. 1B',
    },
    {
        Molecule_ID: '928-96-1',
        Molecule: 'cis-hex-3-en-1-ol',
        Clas_ID: 'H226',
        Clas: 'Flam. Liq. 3',
    },
    {
        Molecule_ID: '928-96-1',
        Molecule: 'cis-hex-3-en-1-ol',
        Clas_ID: 'H319',
        Clas: 'Eye Irrit. 2',
    },
    {
        Molecule_ID: '97-64-3',
        Molecule: 'ethyl lactate',
        Clas_ID: 'H226',
        Clas: 'Flam. Liq. 3',
    },
    {
        Molecule_ID: '97-64-3',
        Molecule: 'ethyl lactate',
        Clas_ID: 'H318',
        Clas: 'Eye Dam. 1',
    },
    {
        Molecule_ID: '97-64-3',
        Molecule: 'ethyl lactate',
        Clas_ID: 'H335',
        Clas: 'STOT SE 3 (H335)',
    },
    {
        Molecule_ID: '115-95-7',
        Molecule: 'linalyl acetate',
        Clas_ID: 'H319',
        Clas: 'Eye Irrit. 2',
    },
    {
        Molecule_ID: '115-95-7',
        Molecule: 'linalyl acetate',
        Clas_ID: 'H315',
        Clas: 'Skin Irrit. 2',
    },
    {
        Molecule_ID: '115-95-7',
        Molecule: 'linalyl acetate',
        Clas_ID: 'H317-1B',
        Clas: 'Skin Sens. 1B',
    },
    {
        Molecule_ID: '5989-27-5',
        Molecule: 'd-limonène',
        Clas_ID: 'H400',
        Clas: 'Aquatic Acute 1',
    },
    {
        Molecule_ID: '5989-27-5',
        Molecule: 'd-limonène',
        Clas_ID: 'H410',
        Clas: 'Aquatic Chronic 1',
    },
    {
        Molecule_ID: '5989-27-5',
        Molecule: 'd-limonène',
        Clas_ID: 'H226',
        Clas: 'Flam. Liq. 3',
    },
    {
        Molecule_ID: '5989-27-5',
        Molecule: 'd-limonène',
        Clas_ID: 'H315',
        Clas: 'Skin Irrit. 2',
    },
    {
        Molecule_ID: '5989-27-5',
        Molecule: 'd-limonène',
        Clas_ID: 'H317-1',
        Clas: 'Skin Sens. 1',
    },
    {
        Molecule_ID: '5989-27-5',
        Molecule: 'd-limonène',
        Clas_ID: 'H304',
        Clas: 'Asp. Tox. 1',
    },
    {
        Molecule_ID: '51115-67-4',
        Molecule: '2-isopropyl-N,2,3-trimethylbutyramide',
        Clas_ID: 'H302',
        Clas: 'Acute Tox. 4 Oral',
    },
    {
        Molecule_ID: '78-93-3',
        Molecule: 'butanone',
        Clas_ID: 'H225',
        Clas: 'Flam. Liq. 2',
    },
    {
        Molecule_ID: '78-93-3',
        Molecule: 'butanone',
        Clas_ID: 'H319',
        Clas: 'Eye Irrit. 2',
    },
    {
        Molecule_ID: '78-93-3',
        Molecule: 'butanone',
        Clas_ID: 'H336',
        Clas: 'STOT SE 3 (H336)',
    },
    {
        Molecule_ID: '513-86-0',
        Molecule: 'acetoin',
        Clas_ID: 'H226',
        Clas: 'Flam. Liq. 3',
    },
    {
        Molecule_ID: '513-86-0',
        Molecule: 'acetoin',
        Clas_ID: 'H318',
        Clas: 'Eye Dam. 1',
    },
    {
        Molecule_ID: '80-71-7',
        Molecule: 'cyclotène',
        Clas_ID: 'H302',
        Clas: 'Acute Tox. 4 Oral',
    },
    {
        Molecule_ID: '80-71-7',
        Molecule: 'cyclotène',
        Clas_ID: 'H318',
        Clas: 'Eye Dam. 1',
    },
    {
        Molecule_ID: '80-71-7',
        Molecule: 'cyclotène',
        Clas_ID: 'H317-1',
        Clas: 'Skin Sens. 1',
    },
];
