export const saveur_molecule = [
    {
        Saveur_ID: 9,
        Saveur: 'Abricot',
        Molecule_ID: '23696-85-7',
        Molecule: '1-(2,6,6-trimethyl-1,3-cyclohe xadien-1-yl)-2-buten-1-one',
        retenu: 0.08,
    },
    {
        Saveur_ID: 9,
        Saveur: 'Abricot',
        Molecule_ID: '56-81-5',
        Molecule: 'glycerol',
        retenu: 45,
    },
    {
        Saveur_ID: 10,
        Saveur: 'Ananas',
        Molecule_ID: '123-68-2',
        Molecule: 'allyl hexanoate',
        retenu: 0.35,
    },
    {
        Saveur_ID: 10,
        Saveur: 'Ananas',
        Molecule_ID: '3658-77-3',
        Molecule: '4-hydroxy-2,5-dimethylfuran-2 (3H)-one',
        retenu: 0.35,
    },
    {
        Saveur_ID: 10,
        Saveur: 'Ananas',
        Molecule_ID: '56-81-5',
        Molecule: 'glycerol',
        retenu: 45,
    },
    {
        Saveur_ID: 44,
        Saveur: 'Antartick',
        Molecule_ID: '14073-97-3',
        Molecule: 'L-menthan-3-one',
        retenu: 0.25,
    },
    {
        Saveur_ID: 44,
        Saveur: 'Antartick',
        Molecule_ID: '2216-51-5',
        Molecule: 'L-menthol',
        retenu: 3.5,
    },
    {
        Saveur_ID: 44,
        Saveur: 'Antartick',
        Molecule_ID: '56-81-5',
        Molecule: 'glycerol',
        retenu: 45,
    },
    {
        Saveur_ID: 44,
        Saveur: 'Antartick',
        Molecule_ID: '64-17-5',
        Molecule: 'éthanol, alcool éthylique',
        retenu: 1,
    },
    {
        Saveur_ID: 44,
        Saveur: 'Antartick',
        Molecule_ID: '8000-48-4',
        Molecule: 'Eucalyptus globulus, ext.',
        retenu: 0.25,
    },
    {
        Saveur_ID: 11,
        Saveur: 'Banane',
        Molecule_ID: '56-81-5',
        Molecule: 'glycerol',
        retenu: 45,
    },
    {
        Saveur_ID: 11,
        Saveur: 'Banane',
        Molecule_ID: '628-63-7',
        Molecule: 'Amyl acetate common',
        retenu: 0.1,
    },
    {
        Saveur_ID: 36,
        Saveur: 'Bonbonella',
        Molecule_ID: '3658-77-3',
        Molecule: '4-hydroxy-2,5-dimethylfuran-2 (3H)-one',
        retenu: 0.3,
    },
    {
        Saveur_ID: 36,
        Saveur: 'Bonbonella',
        Molecule_ID: '56-81-5',
        Molecule: 'glycerol',
        retenu: 45,
    },
    {
        Saveur_ID: 36,
        Saveur: 'Bonbonella',
        Molecule_ID: '75-18-3',
        Molecule: 'dimethyl sulphide',
        retenu: 0.2,
    },
    {
        Saveur_ID: 37,
        Saveur: 'Café',
        Molecule_ID: '56-81-5',
        Molecule: 'glycerol',
        retenu: 45,
    },
    {
        Saveur_ID: 37,
        Saveur: 'Café',
        Molecule_ID: '8007-00-9',
        Molecule: 'Balsams, Peru',
        retenu: 0.2,
    },
    {
        Saveur_ID: 38,
        Saveur: 'Caramel',
        Molecule_ID: '56-81-5',
        Molecule: 'glycerol',
        retenu: 45,
    },
    {
        Saveur_ID: 29,
        Saveur: 'Cassis',
        Molecule_ID: '56-81-5',
        Molecule: 'glycerol',
        retenu: 45,
    },
    {
        Saveur_ID: 12,
        Saveur: 'Citron',
        Molecule_ID: '64-17-5',
        Molecule: 'éthanol, alcool éthylique',
        retenu: 10.5,
    },
    {
        Saveur_ID: 12,
        Saveur: 'Citron',
        Molecule_ID: '56-81-5',
        Molecule: 'glycerol',
        retenu: 45,
    },
    {
        Saveur_ID: 4,
        Saveur: 'Classic 3BK',
        Molecule_ID: '3658-77-3',
        Molecule: '4-hydroxy-2,5-dimethylfuran-2 (3H)-one',
        retenu: 0.98,
    },
    {
        Saveur_ID: 4,
        Saveur: 'Classic 3BK',
        Molecule_ID: '4940-11-8',
        Molecule: '2-ethyl-3-hydroxy-4-pyrone',
        retenu: 2.94,
    },
    {
        Saveur_ID: 4,
        Saveur: 'Classic 3BK',
        Molecule_ID: '56-81-5',
        Molecule: 'glycerol',
        retenu: 45,
    },
    {
        Saveur_ID: 4,
        Saveur: 'Classic 3BK',
        Molecule_ID: '97-64-3',
        Molecule: 'ethyl lactate',
        retenu: 2.94,
    },
    {
        Saveur_ID: 1,
        Saveur: 'Classic Californian',
        Molecule_ID: '56-81-5',
        Molecule: 'glycerol',
        retenu: 45,
    },
    {
        Saveur_ID: 2,
        Saveur: 'Classic Cubano',
        Molecule_ID: '21834-92-4',
        Molecule: '5-methyl-2-phenylhex-2-enal',
        retenu: 0.14,
    },
    {
        Saveur_ID: 2,
        Saveur: 'Classic Cubano',
        Molecule_ID: '56-81-5',
        Molecule: 'glycerol',
        retenu: 45,
    },
    {
        Saveur_ID: 2,
        Saveur: 'Classic Cubano',
        Molecule_ID: '590-86-3',
        Molecule: 'isovaleraldehyde',
        retenu: 0.16,
    },
    {
        Saveur_ID: 5,
        Saveur: 'Classic French',
        Molecule_ID: '56-81-5',
        Molecule: 'glycerol',
        retenu: 45,
    },
    {
        Saveur_ID: 5,
        Saveur: 'Classic French',
        Molecule_ID: '64-17-5',
        Molecule: 'éthanol, alcool éthylique',
        retenu: 0.8,
    },
    {
        Saveur_ID: 6,
        Saveur: 'Classic Island',
        Molecule_ID: '119-84-6',
        Molecule: '3,4-dihydrocoumarin',
        retenu: 0.7,
    },
    {
        Saveur_ID: 6,
        Saveur: 'Classic Island',
        Molecule_ID: '56-81-5',
        Molecule: 'glycerol',
        retenu: 45,
    },
    {
        Saveur_ID: 6,
        Saveur: 'Classic Island',
        Molecule_ID: '64-17-5',
        Molecule: 'éthanol, alcool éthylique',
        retenu: 0.7,
    },
    {
        Saveur_ID: 3,
        Saveur: 'Classic Menthol',
        Molecule_ID: '56-81-5',
        Molecule: 'glycerol',
        retenu: 45,
    },
    {
        Saveur_ID: 3,
        Saveur: 'Classic Menthol',
        Molecule_ID: '64-17-5',
        Molecule: 'éthanol, alcool éthylique',
        retenu: 1.05,
    },
    {
        Saveur_ID: 7,
        Saveur: 'Classic RY4',
        Molecule_ID: '56-81-5',
        Molecule: 'glycerol',
        retenu: 45,
    },
    {
        Saveur_ID: 7,
        Saveur: 'Classic RY5',
        Molecule_ID: '64-17-5',
        Molecule: 'éthanol, alcool éthylique',
        retenu: 1.4,
    },
    {
        Saveur_ID: 8,
        Saveur: 'Classic US',
        Molecule_ID: '56-81-5',
        Molecule: 'glycerol',
        retenu: 45,
    },
    {
        Saveur_ID: 13,
        Saveur: 'Coco Dream',
        Molecule_ID: '56-81-5',
        Molecule: 'glycerol',
        retenu: 45,
    },
    {
        Saveur_ID: 14,
        Saveur: 'Double Pomme',
        Molecule_ID: '141-78-6',
        Molecule: "acétate d'éthyle",
        retenu: 0.3,
    },
    {
        Saveur_ID: 14,
        Saveur: 'Double Pomme',
        Molecule_ID: '56-81-5',
        Molecule: 'glycerol',
        retenu: 45,
    },
    {
        Saveur_ID: 14,
        Saveur: 'Double Pomme',
        Molecule_ID: '87-44-5',
        Molecule: 'caryophyllene',
        retenu: 0.15,
    },
    {
        Saveur: 'Exotica',
        Molecule_ID: '141-25-3',
        Molecule: '3,7-dimethyloct-7-en-1-ol',
        retenu: 0.5,
    },
    {
        Saveur_ID: 15,
        Saveur: 'Exotica',
        Molecule_ID: '56-81-5',
        Molecule: 'glycerol',
        retenu: 45,
    },
    {
        Saveur_ID: 15,
        Saveur: 'Exotica',
        Molecule_ID: '78-70-6',
        Molecule: 'linalool',
        retenu: 0.2,
    },
    {
        Saveur_ID: 15,
        Saveur: 'Exotica',
        Molecule_ID: '8000-46-2',
        Molecule: 'Oils, geranium',
        retenu: 0.15,
    },
    {
        Saveur_ID: 30,
        Saveur: 'Fraise',
        Molecule_ID: '141-78-6',
        Molecule: "acétate d'éthyle",
        retenu: 0.3,
    },
    {
        Saveur_ID: 30,
        Saveur: 'Fraise',
        Molecule_ID: '56-81-5',
        Molecule: 'glycerol',
        retenu: 45,
    },
    {
        Saveur_ID: 31,
        Saveur: 'Framboise',
        Molecule_ID: '123-51-3',
        Molecule: '3-methylbutan-1-ol',
        retenu: 15,
    },
    {
        Saveur_ID: 31,
        Saveur: 'Framboise',
        Molecule_ID: '123-92-2',
        Molecule: "acétate d'isopentyle",
        retenu: 15,
    },
    {
        Saveur_ID: 31,
        Saveur: 'Framboise',
        Molecule_ID: '141-78-6',
        Molecule: "acétate d'éthyle",
        retenu: 0.14,
    },
    {
        Saveur_ID: 31,
        Saveur: 'Framboise',
        Molecule_ID: '23696-85-7',
        Molecule: '1-(2,6,6-trimethyl-1,3-cyclohe xadien-1-yl)-2-buten-1-one',
        retenu: 15,
    },
    {
        Saveur_ID: 31,
        Saveur: 'Framboise',
        Molecule_ID: '56-81-5',
        Molecule: 'glycerol',
        retenu: 45,
    },
    {
        Saveur_ID: 31,
        Saveur: 'Framboise',
        Molecule_ID: '64-19-7',
        Molecule: 'acide acétique',
        retenu: 0.14,
    },
    {
        Saveur_ID: 31,
        Saveur: 'Framboise',
        Molecule_ID: '928-96-1',
        Molecule: 'cis-hex-3-en-1-ol',
        retenu: 1.4,
    },
    {
        Saveur: 'Fruit de la Passion',
        Molecule_ID: '14901-07-6',
        Molecule: '4-(2,6,6-trimethylcyclohex-1-ene-1-yl)-but-3-ene-2-one',
        retenu: 0.15,
    },
    {
        Saveur_ID: 16,
        Saveur: 'Fruit de la Passion',
        Molecule_ID: '16409-43-1',
        Molecule: 'tetrahydro-4-methyl-2-(2-methylprop-1-enyl)pyran',
        retenu: 0.15,
    },
    {
        Saveur_ID: 16,
        Saveur: 'Fruit de la Passion',
        Molecule_ID: '56-81-5',
        Molecule: 'glycerol',
        retenu: 45,
    },
    {
        Saveur_ID: 16,
        Saveur: 'Fruit de la Passion',
        Molecule_ID: '8008-56-8',
        Molecule: 'Lemon Oil',
        retenu: 0.2,
    },
    {
        Saveur_ID: 17,
        Saveur: 'Fruit du Dragon',
        Molecule_ID: '56-81-5',
        Molecule: 'glycerol',
        retenu: 45,
    },
    {
        Saveur_ID: 17,
        Saveur: 'Fruit du Dragon',
        Molecule_ID: '8008-56-8',
        Molecule: 'Lemon Oil',
        retenu: 2.1,
    },
    {
        Saveur_ID: 17,
        Saveur: 'Fruit du Dragon',
        Molecule_ID: '84961-46-6',
        Molecule: 'cinnamomum cassias ext.',
        retenu: 1.4,
    },
    {
        Saveur_ID: 17,
        Saveur: 'Fruit du Dragon',
        Molecule_ID: '141-78-6',
        Molecule: "acétate d'éthyle",
        retenu: 0.04,
    },
    {
        Saveur_ID: 17,
        Saveur: 'Fruit du Dragon',
        Molecule_ID: '3658-77-3',
        Molecule: '4-hydroxy-2,5-dimethylfuran-2 (3H)-one',
        retenu: 0.04,
    },
    {
        Saveur_ID: 33,
        Saveur: 'Fruits des Bois',
        Molecule_ID: '141-78-6',
        Molecule: "acétate d'éthyle",
        retenu: 0.25,
    },
    {
        Saveur_ID: 33,
        Saveur: 'Fruits des Bois',
        Molecule_ID: '56-81-5',
        Molecule: 'glycerol',
        retenu: 45,
    },
    {
        Saveur_ID: 32,
        Saveur: 'Fruits Rouges',
        Molecule_ID: '56-81-5',
        Molecule: 'glycerol',
        retenu: 45,
    },
    {
        Saveur_ID: 18,
        Saveur: 'Kiwi',
        Molecule_ID: '141-78-6',
        Molecule: "acétate d'éthyle",
        retenu: 0.25,
    },
    {
        Saveur_ID: 18,
        Saveur: 'Kiwi',
        Molecule_ID: '3658-77-3',
        Molecule: '4-hydroxy-2,5-dimethylfuran-2 (3H)-one',
        retenu: 0.05,
    },
    {
        Saveur_ID: 18,
        Saveur: 'Kiwi',
        Molecule_ID: '56-81-5',
        Molecule: 'glycerol',
        retenu: 45,
    },
    {
        Saveur_ID: 19,
        Saveur: 'Litchi',
        Molecule_ID: '106-22-9',
        Molecule: 'DL-Citronellol',
        retenu: 0.15,
    },
    {
        Saveur_ID: 19,
        Saveur: 'Litchi',
        Molecule_ID: '106-24-1',
        Molecule: 'geraniol',
        retenu: 0.15,
    },
    {
        Saveur_ID: 19,
        Saveur: 'Litchi',
        Molecule_ID: '56-81-5',
        Molecule: 'glycerol',
        retenu: 45,
    },
    {
        Saveur_ID: 20,
        Saveur: 'Mangue',
        Molecule_ID: '3658-77-3',
        Molecule: '4-hydroxy-2,5-dimethylfuran-2 (3H)-one',
        retenu: 1.1,
    },
    {
        Saveur_ID: 20,
        Saveur: 'Mangue',
        Molecule_ID: '38462-22-5',
        Molecule: 'para-mentha-8-thiolone',
        retenu: 1,
    },
    {
        Saveur_ID: 20,
        Saveur: 'Mangue',
        Molecule_ID: '56-81-5',
        Molecule: 'glycerol',
        retenu: 45,
    },
    {
        Saveur_ID: 20,
        Saveur: 'Mangue',
        Molecule_ID: '78-70-6',
        Molecule: 'linalool',
        retenu: 0.9,
    },
    {
        Saveur_ID: 20,
        Saveur: 'Mangue',
        Molecule_ID: '123-92-2',
        Molecule: "acétate d'isopentyle",
        retenu: 1.1,
    },
    {
        Saveur_ID: 21,
        Saveur: 'Melon',
        Molecule_ID: '56-81-5',
        Molecule: 'glycerol',
        retenu: 45,
    },
    {
        Saveur_ID: 21,
        Saveur: 'Melon',
        Molecule_ID: '123-92-2',
        Molecule: "acétate d'isopentyle",
        retenu: 0.35,
    },
    {
        Saveur_ID: 21,
        Saveur: 'Melon',
        Molecule_ID: '110-19-0',
        Molecule: "acétate d'isobutyle",
        retenu: 0.35,
    },
    {
        Saveur_ID: 21,
        Saveur: 'Melon',
        Molecule_ID: '141-78-6',
        Molecule: "acétate d'éthyle",
        retenu: 0.35,
    },

    {
        Saveur_ID: 45,
        Saveur: 'Menthe Fraiche',
        Molecule_ID: '2216-51-5',
        Molecule: 'L-menthol',
        retenu: 2.8,
    },
    {
        Saveur_ID: 45,
        Saveur: 'Menthe Fraiche',
        Molecule_ID: '491-07-6',
        Molecule: 'isomenthone',
        retenu: 0.4,
    },
    {
        Saveur_ID: 45,
        Saveur: 'Menthe Fraiche',
        Molecule_ID: '56-81-5',
        Molecule: 'glycerol',
        retenu: 45,
    },
    {
        Saveur_ID: 35,
        Saveur: 'Mûre',
        Molecule_ID: '56-81-5',
        Molecule: 'glycerol',
        retenu: 45,
    },
    {
        Saveur_ID: 35,
        Saveur: 'Mûre',
        Molecule_ID: '77-83-8',
        Molecule: 'ethyl 2,3-epoxy-3-phenylbutyrate',
        retenu: 0.15,
    },
    {
        Saveur_ID: 34,
        Saveur: 'Myrtille',
        Molecule_ID: '123-92-2',
        Molecule: "acétate d'isopentyle",
        retenu: 0.15,
    },
    {
        Saveur_ID: 34,
        Saveur: 'Myrtille',
        Molecule_ID: '56-81-5',
        Molecule: 'glycerol',
        retenu: 45,
    },
    {
        Saveur_ID: 39,
        Saveur: 'Noisette Gourmande',
        Molecule_ID: '102322-83-8',
        Molecule: '2-Hepten-4-one, 5-methyl-, (2E)-',
        retenu: 0.02,
    },
    {
        Saveur_ID: 39,
        Saveur: 'Noisette Gourmande',
        Molecule_ID: '56-81-5',
        Molecule: 'glycerol',
        retenu: 45,
    },
    {
        Saveur_ID: 43,
        Saveur: 'Nougat',
        Molecule_ID: '56-81-5',
        Molecule: 'glycerol',
        retenu: 45,
    },
    {
        Saveur_ID: 22,
        Saveur: 'Orange',
        Molecule_ID: '5392-40-5',
        Molecule: 'citral',
        retenu: 0.3,
    },
    {
        Saveur_ID: 22,
        Saveur: 'Orange',
        Molecule_ID: '56-81-5',
        Molecule: 'glycerol',
        retenu: 45,
    },
    {
        Saveur_ID: 22,
        Saveur: 'Orange',
        Molecule_ID: '7212-44-4',
        Molecule: '3,7,11-trimethyldodeca-1,6,10-trien-3-ol,mixed isomers',
        retenu: 0.2,
    },
    {
        Saveur_ID: 22,
        Saveur: 'Orange',
        Molecule_ID: '8008-26-2',
        Molecule: 'Extrait de citron. Citrus aurantifolia.',
        retenu: 0.25,
    },
    {
        Saveur_ID: 0,
        Saveur: 'Pampelmo',
        Molecule_ID: '56-81-5',
        Molecule: 'glycerol',
        retenu: 45,
    },
    {
        Saveur_ID: 0,
        Saveur: 'Pampelmo',
        Molecule_ID: '77-83-8',
        Molecule: 'ethyl 2,3-epoxy-3-phenylbutyrate',
        retenu: 0.15,
    },
    {
        Saveur_ID: 23,
        Saveur: 'Pastèque',
        Molecule_ID: '110-19-0',
        Molecule: "acétate d'isobutyle",
        retenu: 0.7,
    },
    {
        Saveur_ID: 23,
        Saveur: 'Pastèque',
        Molecule_ID: '141-78-6',
        Molecule: "acétate d'éthyle",
        retenu: 0.7,
    },
    {
        Saveur_ID: 23,
        Saveur: 'Pastèque',
        Molecule_ID: '56-81-5',
        Molecule: 'glycerol',
        retenu: 45,
    },
    {
        Saveur_ID: 25,
        Saveur: 'Pêche Blanche',
        Molecule_ID: '56-81-5',
        Molecule: 'glycerol',
        retenu: 45,
    },
    {
        Saveur_ID: 24,
        Saveur: 'Pomme Paradis',
        Molecule_ID: '3658-77-3',
        Molecule: '4-hydroxy-2,5-dimethylfuran-2 (3H)-one',
        retenu: 0.11,
    },
    {
        Saveur_ID: 24,
        Saveur: 'Pomme Paradis',
        Molecule_ID: '56-81-5',
        Molecule: 'glycerol',
        retenu: 45,
    },
    {
        Saveur_ID: 24,
        Saveur: 'Pomme Paradis',
        Molecule_ID: '87-44-5',
        Molecule: 'caryophyllene',
        retenu: 0.15,
    },
    {
        Saveur_ID: 40,
        Saveur: 'Réglisse',
        Molecule_ID: '4180-23-8',
        Molecule: '(E)-anethole',
        retenu: 0.35,
    },
    {
        Saveur_ID: 40,
        Saveur: 'Réglisse',
        Molecule_ID: '56-81-5',
        Molecule: 'glycerol',
        retenu: 45,
    },
    {
        Saveur_ID: 41,
        Saveur: 'Vanille Custard',
        Molecule_ID: '105-13-5',
        Molecule: '4-methoxybenzyl alcohol',
        retenu: 0.15,
    },
    {
        Saveur_ID: 41,
        Saveur: 'Vanille Custard',
        Molecule_ID: '121-33-5',
        Molecule: 'vanillin',
        retenu: 1.1,
    },
    {
        Saveur_ID: 41,
        Saveur: 'Vanille Custard',
        Molecule_ID: '56-81-5',
        Molecule: 'glycerol',
        retenu: 45,
    },
    {
        Saveur_ID: 42,
        Saveur: 'Vanille Ice Cream',
        Molecule_ID: '105-13-5',
        Molecule: '4-methoxybenzyl alcohol',
        retenu: 0.15,
    },
    {
        Saveur_ID: 42,
        Saveur: 'Vanille Ice Cream',
        Molecule_ID: '56-81-5',
        Molecule: 'glycerol',
        retenu: 45,
    },
    {
        Saveur_ID: 26,
        Saveur: 'Bonbon Arlequin',
        Molecule_ID: '56-81-5',
        Molecule: 'glycerol',
        retenu: 45,
    },
    {
        Saveur_ID: 26,
        Saveur: 'Bonbon Arlequin',
        Molecule_ID: '123-92-2',
        Molecule: "acétate d'isopentyle",
        retenu: 2,
    },
    {
        Saveur_ID: 26,
        Saveur: 'Bonbon Arlequin',
        Molecule_ID: '115-95-7',
        Molecule: 'linalyl acetate',
        retenu: 0.25,
    },
    {
        Saveur_ID: 26,
        Saveur: 'Bonbon Arlequin',
        Molecule_ID: '123-51-3',
        Molecule: '3-methylbutan-1-ol',
        retenu: 0.25,
    },
    {
        Saveur_ID: 27,
        Saveur: 'Energy Drink',
        Molecule_ID: '56-81-5',
        Molecule: 'glycerol',
        retenu: 45,
    },
    {
        Saveur_ID: 27,
        Saveur: 'Energy Drink',
        Molecule_ID: '123-51-3',
        Molecule: '3-methylbutan-1-ol',
        retenu: 0.14,
    },
    {
        Saveur_ID: 27,
        Saveur: 'Energy Drink',
        Molecule_ID: '64-19-7',
        Molecule: 'acide acétique',
        retenu: 0.14,
    },
    {
        Saveur_ID: 27,
        Saveur: 'Energy Drink',
        Molecule_ID: '141-78-6',
        Molecule: "acétate d'éthyle",
        retenu: 0.04,
    },
    {
        Saveur_ID: 28,
        Saveur: 'Dragibo',
        Molecule_ID: '56-81-5',
        Molecule: 'glycerol',
        retenu: 45,
    },
    {
        Saveur_ID: 46,
        Saveur: 'Menthe Chlorophylle',
        Molecule_ID: '56-81-5',
        Molecule: 'glycerol',
        retenu: 45,
    },
    {
        Saveur_ID: 46,
        Saveur: 'Menthe Chlorophylle',
        Molecule_ID: '51115-67-4',
        Molecule: '2-isopropyl-N,2,3-trimethylbutyramide',
        retenu: 1.5,
    },
    {
        Saveur_ID: 46,
        Saveur: 'Menthe Chlorophylle',
        Molecule_ID: '5989-27-5',
        Molecule: 'd-limonène',
        retenu: 0.25,
    },
];
