# get the HASURA_GRAPHQL_ADMIN_SECRET from .env
console:
	npx hasura console --admin-secret "hasuraadminpassword"

# hasura squash migrations
# npx hasura migrate squash --admin-secret "hasuraadminpassword" --name "all-item-tables" --from 1626124078317 --database-name default
#

# hasura migration
# npx hasura metadata apply --endpoint "https://"  --admin-secret ""
#